// นิยามทะเบียน: เพิ่มทะเบียนใหม่ได้โดยเพิ่มค่าในไฟล์นี้ ไม่ต้องเขียนหน้าใหม่
const UNITS = ['ธุรการ', 'การเงินและบัญชี', 'พัสดุ', 'ส่งเสริมป้องกันควบคุมโรค', 'เวชปฏิบัติครอบครัว', 'ผู้อำนวยการ'];

// รายชื่อ "ถึง" มาตรฐานของหนังสือส่ง (เลือกจากรายการ หรือเลือก "อื่น ๆ" แล้วพิมพ์เอง)
export const OUTGOING_TO_OPTIONS = [
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร',
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร (ผ่านผู้อำนวยการกองสาธารณสุข)',
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร (ผ่านผู้อำนวยการกองคลัง)',
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร (ผ่านผู้อำนวยการกองพัสดุและทรัพย์สิน)',
  'ผู้อำนวยการโรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองสนม',
  'ผู้จัดการธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร (สาขาธาตุนาเวง)',
  'ผู้จัดการธนาคารกรุงไทย',
  'ผู้อำนวยการโรงพยาบาลสกลนคร',
  'ผู้ใหญ่บ้าน',
  'ผู้จัดการร้านหนึ่งก๊อปปี้',
  'ผู้จัดการสหกรณ์การเกษตรเมืองสกลนคร จำกัด',
];

export const REGISTRIES = {
  incoming: {
    key: 'incoming',
    path: '/incoming',
    title: 'ทะเบียนหนังสือรับ',
    noun: 'หนังสือรับ',
    numberField: 'receiveNo',
    numberLabel: 'เลขรับ',
    dateField: 'receiveDate',
    statusField: 'status',
    dueField: 'dueDate',
    doneStatus: 'ดำเนินการแล้ว',
    groupField: 'unit',
    statusColors: {
      'รอดำเนินการ': 'bg-amber-100 text-amber-800',
      'กำลังดำเนินการ': 'bg-blue-100 text-blue-800',
      'ดำเนินการแล้ว': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'receiveNo', label: 'เลขรับ', type: 'text', auto: true, list: true, search: true },
      { key: 'receiveDate', label: 'วันที่รับ', type: 'date', required: true, list: true },
      { key: 'docNo', label: 'เลขที่หนังสือ', type: 'text', required: true, list: true, search: true },
      { key: 'docDate', label: 'ลงวันที่', type: 'date' },
      { key: 'from', label: 'จาก', type: 'text', required: true, list: true, search: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'to', label: 'ถึง', type: 'text', search: true },
      { key: 'owner', label: 'ผู้รับผิดชอบ', type: 'text', list: true, search: true },
      { key: 'unit', label: 'กลุ่มงาน', type: 'select', options: UNITS },
      { key: 'urgency', label: 'ความเร่งด่วน', type: 'select', options: ['ปกติ', 'ด่วน', 'ด่วนมาก', 'ด่วนที่สุด'], default: 'ปกติ' },
      { key: 'secrecy', label: 'ชั้นความลับ', type: 'select', options: ['ปกติ', 'ลับ', 'ลับมาก', 'ลับที่สุด'], default: 'ปกติ' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['รอดำเนินการ', 'กำลังดำเนินการ', 'ดำเนินการแล้ว'], default: 'รอดำเนินการ', list: true },
      { key: 'dueDate', label: 'กำหนดดำเนินการ', type: 'date' },
      { key: 'actionDate', label: 'วันที่ดำเนินการ', type: 'date' },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'F5A623',
    reportColumns: ['receiveNo', 'receiveDate', 'from', 'to', 'subject', 'docDate'],
  },
  outgoing: {
    key: 'outgoing',
    path: '/outgoing',
    title: 'ทะเบียนหนังสือส่ง',
    noun: 'หนังสือส่ง',
    numberField: 'sendNo',
    numberLabel: 'เลขส่ง',
    dateField: 'sendDate',
    statusField: 'status',
    doneStatus: 'ส่งแล้ว',
    pendingStatus: 'ร่าง',
    groupField: 'unit',
    statusColors: {
      'ร่าง': 'bg-amber-100 text-amber-800',
      'ส่งแล้ว': 'bg-blue-100 text-blue-800',
      'ยืนยันรับแล้ว': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'sendNo', label: 'เลขส่ง', type: 'text', auto: true, list: true, search: true },
      { key: 'sendDate', label: 'วันที่ส่ง', type: 'date', required: true, list: true },
      { key: 'docNo', label: 'เลขที่หนังสือ', type: 'text', required: true, list: true, search: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'to', label: 'ถึง', type: 'select-other', options: OUTGOING_TO_OPTIONS, required: true, list: true, search: true },
      { key: 'owner', label: 'ผู้รับผิดชอบ', type: 'text', search: true },
      { key: 'unit', label: 'กลุ่มงาน', type: 'select', options: UNITS },
      { key: 'method', label: 'วิธีส่ง', type: 'select', options: ['ไปรษณีย์', 'ส่งด้วยตนเอง', 'อีเมล', 'ระบบสารบรรณอิเล็กทรอนิกส์', 'อื่น ๆ'], default: 'ไปรษณีย์' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['ร่าง', 'ส่งแล้ว', 'ยืนยันรับแล้ว'], default: 'ร่าง', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'F6C90E',
    reportColumns: ['sendNo', 'sendDate', 'to', 'subject', 'note'],
  },
  vehicle: {
    key: 'vehicle',
    path: '/vehicle',
    title: 'ทะเบียนควบคุมยานพาหนะ',
    noun: 'การใช้รถ',
    numberField: 'tripNo',
    numberLabel: 'เลขที่ใช้รถ',
    dateField: 'useDate',
    statusField: 'status',
    doneStatus: 'เสร็จสิ้น',
    groupField: 'plate',
    statusColors: {
      'ขออนุมัติ': 'bg-amber-100 text-amber-800',
      'กำลังใช้งาน': 'bg-blue-100 text-blue-800',
      'เสร็จสิ้น': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'tripNo', label: 'เลขที่ใช้รถ', type: 'text', auto: true, list: true, search: true },
      { key: 'useDate', label: 'วันที่ใช้รถ', type: 'date', required: true, list: true },
      { key: 'plate', label: 'ทะเบียนรถ', type: 'text', required: true, list: true, search: true },
      { key: 'purpose', label: 'ภารกิจ/จุดหมาย', type: 'textarea', required: true, list: true, search: true },
      { key: 'requester', label: 'ผู้ขอใช้รถ', type: 'text', list: true, search: true },
      { key: 'unit', label: 'กลุ่มงาน', type: 'select', options: UNITS },
      { key: 'driver', label: 'ผู้ขับรถ', type: 'text', search: true },
      { key: 'timeOut', label: 'เวลาออก', type: 'text' },
      { key: 'timeIn', label: 'เวลากลับ', type: 'text' },
      { key: 'odoStart', label: 'เลขไมล์เริ่มต้น', type: 'text' },
      { key: 'odoEnd', label: 'เลขไมล์สิ้นสุด', type: 'text' },
      { key: 'fuelCost', label: 'ค่าน้ำมัน (บาท)', type: 'text' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['ขออนุมัติ', 'กำลังใช้งาน', 'เสร็จสิ้น'], default: 'ขออนุมัติ', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: '4FA8E0',
    reportColumns: ['tripNo', 'useDate', 'plate', 'driver', 'purpose', 'requester', 'status'],
  },
  duty: {
    key: 'duty',
    path: '/duty',
    title: 'แผนปฏิบัติงานเวรนอกเวลาประจำเดือน',
    noun: 'เวรนอกเวลา',
    numberField: 'dutyNo',
    numberLabel: 'เลขที่',
    dateField: 'dutyDate',
    statusField: 'status',
    doneStatus: 'ปฏิบัติงานแล้ว',
    groupField: 'dutyType',
    statusColors: {
      'วางแผน': 'bg-amber-100 text-amber-800',
      'ปฏิบัติงานแล้ว': 'bg-emerald-100 text-emerald-800',
      'ยกเลิก': 'bg-slate-200 text-slate-600',
    },
    fields: [
      { key: 'dutyNo', label: 'เลขที่', type: 'text', auto: true, list: true, search: true },
      { key: 'dutyDate', label: 'วันที่ปฏิบัติเวร', type: 'date', required: true, list: true },
      { key: 'dutyType', label: 'ประเภทเวร', type: 'select', options: ['เวรเช้า', 'เวรบ่าย', 'เวรดึก', 'เวรวันหยุดนักขัตฤกษ์'], default: 'เวรบ่าย', list: true },
      { key: 'timeRange', label: 'เวลาปฏิบัติงาน', type: 'text', list: true },
      { key: 'staffName', label: 'ผู้ปฏิบัติหน้าที่เวร', type: 'text', required: true, list: true, search: true },
      { key: 'position', label: 'ตำแหน่ง', type: 'text', search: true },
      { key: 'location', label: 'จุดปฏิบัติงาน', type: 'text', search: true },
      { key: 'approver', label: 'ผู้อนุมัติ/ผู้สั่งการ', type: 'text' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['วางแผน', 'ปฏิบัติงานแล้ว', 'ยกเลิก'], default: 'วางแผน', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: '7FCC9E',
    reportColumns: ['dutyNo', 'dutyDate', 'dutyType', 'timeRange', 'staffName', 'location', 'status'],
  },
  homevisit: {
    key: 'homevisit',
    path: '/homevisit',
    title: 'แผนปฏิบัติงานและรายงานผลการเยี่ยมบ้านเชิงรุกในชุมชนประจำเดือน',
    noun: 'การเยี่ยมบ้าน',
    numberField: 'visitNo',
    numberLabel: 'เลขที่',
    dateField: 'visitDate',
    statusField: 'status',
    doneStatus: 'ดำเนินการแล้ว',
    groupField: 'targetGroup',
    statusColors: {
      'วางแผน': 'bg-amber-100 text-amber-800',
      'ดำเนินการแล้ว': 'bg-emerald-100 text-emerald-800',
      'เลื่อน/ยกเลิก': 'bg-slate-200 text-slate-600',
    },
    fields: [
      { key: 'visitNo', label: 'เลขที่', type: 'text', auto: true, list: true, search: true },
      { key: 'visitDate', label: 'วันที่ออกเยี่ยม', type: 'date', required: true, list: true },
      { key: 'village', label: 'หมู่บ้าน/พื้นที่', type: 'text', required: true, list: true, search: true },
      { key: 'targetGroup', label: 'กลุ่มเป้าหมาย', type: 'select', options: ['ผู้สูงอายุ', 'ผู้พิการ', 'หญิงตั้งครรภ์/หลังคลอด', 'ผู้ป่วยติดบ้านติดเตียง', 'ผู้ป่วย NCD', 'เด็กเล็ก', 'อื่น ๆ'], list: true },
      { key: 'team', label: 'ทีมผู้ออกปฏิบัติงาน', type: 'text', required: true, search: true },
      { key: 'planDetail', label: 'แผนการปฏิบัติงาน', type: 'textarea' },
      { key: 'visitedCount', label: 'จำนวนที่ออกเยี่ยม (ราย)', type: 'text', list: true },
      { key: 'resultDetail', label: 'ผลการปฏิบัติงาน', type: 'textarea' },
      { key: 'problem', label: 'ปัญหา/อุปสรรค', type: 'textarea' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['วางแผน', 'ดำเนินการแล้ว', 'เลื่อน/ยกเลิก'], default: 'วางแผน', list: true },
    ],
    reportColor: 'B48EAD',
    reportColumns: ['visitNo', 'visitDate', 'village', 'targetGroup', 'team', 'visitedCount', 'status'],
  },
};
