// นิยามทะเบียน: เพิ่มทะเบียนใหม่ได้โดยเพิ่มค่าในไฟล์นี้ ไม่ต้องเขียนหน้าใหม่
const UNITS = ['ธุรการ', 'การเงินและบัญชี', 'พัสดุ', 'ส่งเสริมป้องกันควบคุมโรค', 'เวชปฏิบัติครอบครัว', 'ผู้อำนวยการ'];

// ตำแหน่งผู้อำนวยการ รพ.สต. — ใช้เป็นช้อยตรึงไว้ (pinned) และค่าเริ่มต้นของช่อง "ถึง" ในทะเบียนหนังสือรับ
export const DIRECTOR_TITLE = 'ผู้อำนวยการโรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองสนม';

// รายชื่อ "ถึง" มาตรฐานของหนังสือส่ง (เลือกจากรายการ หรือเลือก "อื่น ๆ" แล้วพิมพ์เอง)
export const OUTGOING_TO_OPTIONS = [
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร',
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร (ผ่านผู้อำนวยการกองสาธารณสุข)',
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร (ผ่านผู้อำนวยการกองคลัง)',
  'นายกองค์การบริหารส่วนจังหวัดสกลนคร (ผ่านผู้อำนวยการกองพัสดุและทรัพย์สิน)',
  'ผู้อำนวยการโรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองสนม',
  'ผู้จัดการธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร (สาขาธาตุนาเวง)',
  'ผู้จัดการธนาคารกรุงไทย',
  'ผู้อำนวยการโรงพยาบาลสกลนคร',
  'ผู้ใหญ่บ้าน',
  'ผู้จัดการร้านหนึ่งก๊อปปี้',
  'ผู้จัดการสหกรณ์การเกษตรเมืองสกลนคร จำกัด',
];

export const REGISTRIES = {
  incoming: {
    key: 'incoming',
    path: '/incoming',
    emoji: '📥',
    title: 'ทะเบียนหนังสือรับ',
    noun: 'หนังสือรับ',
    numberField: 'receiveNo',
    numberLabel: 'เลขรับ',
    dateField: 'receiveDate',
    statusField: 'status',
    dueField: 'dueDate',
    doneStatus: 'ดำเนินการแล้ว',
    statusColors: {
      'รอดำเนินการ': 'bg-amber-100 text-amber-800',
      'กำลังดำเนินการ': 'bg-blue-100 text-blue-800',
      'ส่งให้ ผอ.รพ.สต.พิจารณามอบหมาย': 'bg-purple-100 text-purple-800',
      'ดำเนินการแล้ว': 'bg-emerald-100 text-emerald-800',
    },
    // วันที่รับ/เวลารับ เป็นค่าที่ระบบกำหนดให้อัตโนมัติตามเวลาจริงที่กดบันทึก (auto: true) แก้ไขเองไม่ได้ เพื่อไม่ให้ขัดกับเลขรับที่ออกอัตโนมัติ
    // ตัดช่อง "เลขที่หนังสือ"/"ลงวันที่" (ของหนังสือต้นฉบับ) ออกแล้วตามคำขอ เหลือเฉพาะเลขรับ/วันที่รับ/เวลารับที่ระบบออกให้อัตโนมัติ
    fields: [
      { key: 'receiveNo', label: 'เลขรับ', type: 'text', auto: true, list: true, search: true },
      { key: 'receiveDate', label: 'วันที่รับ', type: 'date', auto: true, list: true },
      { key: 'receiveTime', label: 'เวลารับ', type: 'text', auto: true, list: true },
      { key: 'from', label: 'จาก', type: 'text', required: true, list: true, search: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'to', label: 'ถึง', type: 'select-users', pinnedOption: DIRECTOR_TITLE, default: DIRECTOR_TITLE, search: true },
      { key: 'urgency', label: 'ความเร่งด่วน', type: 'select', options: ['ปกติ', 'ด่วน', 'ด่วนมาก', 'ด่วนที่สุด'], default: 'ปกติ' },
      { key: 'secrecy', label: 'ชั้นความลับ', type: 'select', options: ['ปกติ', 'ลับ', 'ลับมาก', 'ลับที่สุด'], default: 'ปกติ' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['รอดำเนินการ', 'กำลังดำเนินการ', 'ส่งให้ ผอ.รพ.สต.พิจารณามอบหมาย', 'ดำเนินการแล้ว'], default: 'รอดำเนินการ', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'F5A623',
    reportColumns: ['receiveNo', 'receiveDate', 'from', 'to', 'subject', 'status'],
  },
  outgoing: {
    key: 'outgoing',
    path: '/outgoing',
    emoji: '📤',
    title: 'ทะเบียนหนังสือส่ง',
    noun: 'หนังสือส่ง',
    numberField: 'sendNo',
    numberLabel: 'เลขส่ง',
    dateField: 'sendDate',
    fields: [
      { key: 'sendNo', label: 'เลขส่ง', type: 'text', auto: true, list: true, search: true },
      { key: 'sendDate', label: 'วันที่ส่ง', type: 'date', required: true, list: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      // เลือกจากช้อยรายชื่อหน่วยงานที่ใช้บ่อย หรือเลือก "อื่นๆ (ระบุ)" แล้วช่องพิมพ์เองจะปรากฏขึ้นอัตโนมัติ
      { key: 'to', label: 'ถึง', type: 'select-other', options: OUTGOING_TO_OPTIONS, required: true, list: true, search: true },
      { key: 'owner', label: 'ผู้รับผิดชอบ', type: 'select-users', list: true, search: true },
      { key: 'method', label: 'วิธีส่ง', type: 'select', options: ['ไปรษณีย์', 'ส่งด้วยตนเอง', 'อีเมล', 'ระบบสารบรรณอิเล็กทรอนิกส์', 'แจ้งเวียนภายใน รพ.สต.', 'แจ้งเวียนโดย จนท.การเงินและบัญชี', 'อื่น ๆ'], default: 'ไปรษณีย์' },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'F6C90E',
    reportColumns: ['sendNo', 'sendDate', 'to', 'subject', 'note'],
  },
  vehicle: {
    key: 'vehicle',
    path: '/vehicle',
    emoji: '🚗',
    title: 'ทะเบียนควบคุมยานพาหนะ',
    noun: 'การใช้รถ',
    numberField: 'tripNo',
    numberLabel: 'เลขที่ใช้รถ',
    dateField: 'useDate',
    statusField: 'status',
    doneStatus: 'เสร็จสิ้น',
    groupField: 'plate',
    statusColors: {
      'ขออนุมัติ': 'bg-amber-100 text-amber-800',
      'กำลังใช้งาน': 'bg-blue-100 text-blue-800',
      'เสร็จสิ้น': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'tripNo', label: 'เลขที่ใช้รถ', type: 'text', auto: true, list: true, search: true },
      { key: 'useDate', label: 'วันที่ใช้รถ', type: 'date', required: true, list: true },
      { key: 'plate', label: 'ทะเบียนรถ', type: 'text', required: true, list: true, search: true },
      { key: 'purpose', label: 'ภารกิจ/จุดหมาย', type: 'textarea', required: true, list: true, search: true },
      { key: 'requester', label: 'ผู้ขอใช้รถ', type: 'text', list: true, search: true },
      { key: 'unit', label: 'กลุ่มงาน', type: 'select', options: UNITS },
      { key: 'driver', label: 'ผู้ขับรถ', type: 'text', search: true },
      { key: 'timeOut', label: 'เวลาออก', type: 'text' },
      { key: 'timeIn', label: 'เวลากลับ', type: 'text' },
      { key: 'odoStart', label: 'เลขไมล์เริ่มต้น', type: 'text' },
      { key: 'odoEnd', label: 'เลขไมล์สิ้นสุด', type: 'text' },
      { key: 'fuelCost', label: 'ค่าน้ำมัน (บาท)', type: 'text' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['ขออนุมัติ', 'กำลังใช้งาน', 'เสร็จสิ้น'], default: 'ขออนุมัติ', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: '4FA8E0',
    reportColumns: ['tripNo', 'useDate', 'plate', 'driver', 'purpose', 'requester', 'status'],
  },
  duty: {
    key: 'duty',
    path: '/duty',
    emoji: '🌙',
    title: 'แผนปฏิบัติงานเวรนอกเวลาประจำเดือน',
    noun: 'เวรนอกเวลา',
    numberField: 'dutyNo',
    numberLabel: 'เลขที่',
    dateField: 'dutyDate',
    statusField: 'status',
    doneStatus: 'ปฏิบัติงานแล้ว',
    groupField: 'dutyType',
    statusColors: {
      'วางแผน': 'bg-amber-100 text-amber-800',
      'ปฏิบัติงานแล้ว': 'bg-emerald-100 text-emerald-800',
      'ยกเลิก': 'bg-slate-200 text-slate-600',
    },
    fields: [
      { key: 'dutyNo', label: 'เลขที่', type: 'text', auto: true, list: true, search: true },
      { key: 'dutyDate', label: 'วันที่ปฏิบัติเวร', type: 'date', required: true, list: true },
      { key: 'dutyType', label: 'ประเภทเวร', type: 'select', options: ['เวรเช้า', 'เวรบ่าย', 'เวรดึก', 'เวรวันหยุดนักขัตฤกษ์'], default: 'เวรบ่าย', list: true },
      { key: 'timeRange', label: 'เวลาปฏิบัติงาน', type: 'text', list: true },
      { key: 'staffName', label: 'ผู้ปฏิบัติหน้าที่เวร', type: 'text', required: true, list: true, search: true },
      { key: 'position', label: 'ตำแหน่ง', type: 'text', search: true },
      { key: 'location', label: 'จุดปฏิบัติงาน', type: 'text', search: true },
      { key: 'approver', label: 'ผู้อนุมัติ/ผู้สั่งการ', type: 'text' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['วางแผน', 'ปฏิบัติงานแล้ว', 'ยกเลิก'], default: 'วางแผน', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: '7FCC9E',
    reportColumns: ['dutyNo', 'dutyDate', 'dutyType', 'timeRange', 'staffName', 'location', 'status'],
  },
  homevisit: {
    key: 'homevisit',
    path: '/homevisit',
    emoji: '🏠',
    title: 'แผนปฏิบัติงานและรายงานผลการเยี่ยมบ้านเชิงรุกในชุมชนประจำเดือน',
    noun: 'การเยี่ยมบ้าน',
    numberField: 'visitNo',
    numberLabel: 'เลขที่',
    dateField: 'visitDate',
    statusField: 'status',
    doneStatus: 'ดำเนินการแล้ว',
    groupField: 'targetGroup',
    statusColors: {
      'วางแผน': 'bg-amber-100 text-amber-800',
      'ดำเนินการแล้ว': 'bg-emerald-100 text-emerald-800',
      'เลื่อน/ยกเลิก': 'bg-slate-200 text-slate-600',
    },
    fields: [
      { key: 'visitNo', label: 'เลขที่', type: 'text', auto: true, list: true, search: true },
      { key: 'visitDate', label: 'วันที่ออกเยี่ยม', type: 'date', required: true, list: true },
      { key: 'village', label: 'หมู่บ้าน/พื้นที่', type: 'text', required: true, list: true, search: true },
      { key: 'targetGroup', label: 'กลุ่มเป้าหมาย', type: 'select', options: ['ผู้สูงอายุ', 'ผู้พิการ', 'หญิงตั้งครรภ์/หลังคลอด', 'ผู้ป่วยติดบ้านติดเตียง', 'ผู้ป่วย NCD', 'เด็กเล็ก', 'อื่น ๆ'], list: true },
      { key: 'team', label: 'ทีมผู้ออกปฏิบัติงาน', type: 'text', required: true, search: true },
      { key: 'planDetail', label: 'แผนการปฏิบัติงาน', type: 'textarea' },
      { key: 'visitedCount', label: 'จำนวนที่ออกเยี่ยม (ราย)', type: 'text', list: true },
      { key: 'resultDetail', label: 'ผลการปฏิบัติงาน', type: 'textarea' },
      { key: 'problem', label: 'ปัญหา/อุปสรรค', type: 'textarea' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['วางแผน', 'ดำเนินการแล้ว', 'เลื่อน/ยกเลิก'], default: 'วางแผน', list: true },
    ],
    reportColor: 'B48EAD',
    reportColumns: ['visitNo', 'visitDate', 'village', 'targetGroup', 'team', 'visitedCount', 'status'],
  },

  // ===== ทะเบียนประกอบฎีกาและทะเบียนต่างๆ (เพิ่มตามแบบฟอร์มตัวอย่างที่ส่งมา) =====
  // ลักษณะคอลัมน์อ้างอิงจากไฟล์ PDF ตัวอย่างที่ส่งมาโดยตรง (เลขที่/วันที่/เรื่อง ± จำนวนเงิน)
  // ออกเลขที่อัตโนมัติและแยกข้อมูลตามปีงบประมาณเหมือนทะเบียนอื่นๆ ในระบบ (createNumbered ผูกกับ fy อัตโนมัติ)
  'reg-orders': {
    key: 'reg-orders',
    path: '/reg-orders',
    emoji: '📜',
    title: 'ทะเบียนเลขคำสั่ง รพ.สต.บ้านหนองสนม',
    noun: 'คำสั่ง',
    numberField: 'orderNo',
    numberLabel: 'เลขที่คำสั่ง',
    dateField: 'orderDate',
    fields: [
      { key: 'orderNo', label: 'เลขที่คำสั่ง', type: 'text', auto: true, list: true, search: true },
      { key: 'orderDate', label: 'วันที่', type: 'date', required: true, list: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'F6C90E',
    reportColumns: ['orderNo', 'orderDate', 'subject'],
  },
  'reg-announce': {
    key: 'reg-announce',
    path: '/reg-announce',
    emoji: '📢',
    title: 'ทะเบียนประกาศ',
    noun: 'ประกาศ',
    numberField: 'announceNo',
    numberLabel: 'เลขที่ประกาศ',
    dateField: 'announceDate',
    fields: [
      { key: 'announceNo', label: 'เลขที่ประกาศ', type: 'text', auto: true, list: true, search: true },
      { key: 'announceDate', label: 'วันที่', type: 'date', required: true, list: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: '8FD9A8',
    reportColumns: ['announceNo', 'announceDate', 'subject'],
  },
  'reg-procurement': {
    key: 'reg-procurement',
    path: '/reg-procurement',
    emoji: '🛒',
    title: 'ทะเบียนใบสั่งซื้อ/สั่งจ้าง',
    noun: 'ใบสั่งซื้อ/สั่งจ้าง',
    numberField: 'poNo',
    numberLabel: 'เลขที่ใบสั่งซื้อ/สั่งจ้าง',
    dateField: 'poDate',
    fields: [
      { key: 'poNo', label: 'เลขที่ใบสั่งซื้อ/สั่งจ้าง', type: 'text', auto: true, list: true, search: true },
      { key: 'poDate', label: 'วันที่', type: 'date', required: true, list: true },
      // เพิ่มตามคำขอ: ชื่อผู้รับใบสั่งซื้อ/สั่งจ้าง (จะเป็นบุคคลธรรมดา ร้าน หจก. หรือบริษัทก็ได้ กรอกเป็นข้อความ)
      { key: 'vendorName', label: 'ชื่อผู้รับใบสั่งซื้อสั่งจ้าง (บุคคลธรรมดา/ร้าน/หจก./บริษัท)', type: 'text', list: true, search: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'FFD400',
    reportColumns: ['poNo', 'poDate', 'vendorName', 'subject'],
  },
  'reg-contract-no': {
    key: 'reg-contract-no',
    path: '/reg-contract-no',
    emoji: '📝',
    title: 'ทะเบียนหนังสือสัญญา',
    noun: 'หนังสือสัญญา',
    numberField: 'contractNo',
    numberLabel: 'เลขที่สัญญา',
    dateField: 'contractDate',
    fields: [
      { key: 'contractNo', label: 'เลขที่สัญญา', type: 'text', auto: true, list: true, search: true },
      { key: 'contractDate', label: 'วันที่', type: 'date', required: true, list: true },
      // เพิ่มตามคำขอ: เลือกประเภทคู่สัญญาจากช้อยก่อน แล้วค่อยกรอก/เลือกชื่อ — ถ้าเป็น "ลูกจ้างชั่วคราว" ให้เปลี่ยนเป็นช้อยเลือกจากทำเนียบบุคลากรแทนช่องพิมพ์ชื่อเอง (เพื่อใช้ในรายงานได้)
      { key: 'partyType', label: 'ประเภทคู่สัญญา', type: 'select', options: ['ร้าน', 'บริษัท', 'หจก.', 'บุคคล', 'ลูกจ้างชั่วคราว', 'ลูกจ้างจ้างเหมาบริการ'], required: true, list: true },
      { key: 'partyName', label: 'ชื่อคู่สัญญา (ร้าน/บริษัท/หจก./บุคคล/ลูกจ้างจ้างเหมาบริการ)', type: 'text', list: true, search: true, showIf: (v) => v.partyType !== 'ลูกจ้างชั่วคราว' },
      { key: 'partyStaff', label: 'เลือกบุคลากร (ลูกจ้างชั่วคราว)', type: 'select-users', list: true, search: true, showIf: (v) => v.partyType === 'ลูกจ้างชั่วคราว' },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: '7ED6A5',
    reportColumns: ['contractNo', 'contractDate', 'partyType', 'partyName', 'partyStaff', 'subject'],
  },
  // เลขที่สัญญาเงินยืมใช้รูปแบบตายตัวเฉพาะของทะเบียนนี้ "B" + เลข 2 หลัก + ปีงบ เช่น B01/2569, B02/2569 ...
  // (numberPrefix/numberDigits ด้านล่าง overide ค่าตั้งค่ากลางของระบบเฉพาะทะเบียนนี้เท่านั้น ไม่กระทบทะเบียนอื่น)
  // การคืนเงินยืม ย้ายมารวมอยู่ในทะเบียนนี้ (ไม่ใช่ทะเบียนแยกอีกต่อไป) — บันทึกผ่านปุ่ม "คืนเงินยืม" ที่ท้ายแต่ละแถวในหน้าทะเบียน
  // สถานะ "repaid" ใช้เป็น statusField/statusColors ของหน้านี้ไปในตัว (แสดงป้ายสี + กรองตามสถานะได้อัตโนมัติ) — ดู src/components/RegistryPage.jsx (isLoan)
  'reg-loan': {
    key: 'reg-loan',
    path: '/reg-loan',
    emoji: '💵',
    title: 'ทะเบียนสัญญาเงินยืม',
    noun: 'สัญญาเงินยืม',
    numberField: 'loanNo',
    numberLabel: 'เลขที่สัญญาเงินยืม',
    numberPrefix: 'B',
    numberDigits: 2,
    dateField: 'loanDate',
    statusField: 'repaid',
    doneStatus: 'ส่งใช้เงินยืมเรียบร้อย',
    statusColors: {
      'สัญญาค้างจ่ายเงินยืม': 'bg-red-100 text-red-800',
      'ส่งใช้เงินยืมเรียบร้อย': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'loanNo', label: 'เลขที่สัญญาเงินยืม', type: 'text', auto: true, list: true, search: true },
      { key: 'loanDate', label: 'วันที่ยืม', type: 'date', required: true, list: true },
      { key: 'borrower', label: 'ชื่อผู้ยืมเงิน', type: 'text', required: true, list: true, search: true },
      { key: 'subject', label: 'ยืมเรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'amount', label: 'จำนวนเงินยืม', type: 'text', list: true },
      { key: 'dueDate', label: 'กำหนดวันส่งใช้', type: 'date', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
      // auto: true = ไม่แสดงในฟอร์มเพิ่ม/แก้ไขทั่วไป ตั้งค่าผ่านปุ่ม "คืนเงินยืม" เท่านั้น (ดูตารางด้านล่าง + ปุ่มท้ายแถว)
      { key: 'repaid', label: 'สถานะการคืนเงินยืม', type: 'select', auto: true, options: ['สัญญาค้างจ่ายเงินยืม', 'ส่งใช้เงินยืมเรียบร้อย'], default: 'สัญญาค้างจ่ายเงินยืม', list: true },
      { key: 'repayDate', label: 'วันที่ส่งใช้เงินยืม', type: 'date', auto: true, list: true },
      { key: 'repayDika', label: 'เลขฎีกาส่งใช้เงินยืม', type: 'text', auto: true, list: true, search: true },
    ],
    reportColor: 'FFC914',
    reportColumns: ['loanNo', 'loanDate', 'borrower', 'subject', 'amount', 'dueDate', 'repaid', 'repayDate', 'repayDika'],
  },
  // แก้ไขจาก "ทะเบียนคุมการจ่ายเบิกจ่ายเล่มเช็ค" เป็น "ทะเบียนคุมการเบิกจ่ายเล่มเช็ค" — ออกแบบใหม่เป็นทะเบียนคุมคลัง (รับเข้า/เบิกออก) คำนวณยอดคงเหลือให้อัตโนมัติทุกครั้งที่บันทึก
  // stockLedger: กำหนดให้หน้า RegistryPage แสดงปุ่ม "เพิ่มเล่มเข้าคลัง"/"เบิกออกจากคลัง" แบบป๊อปอัพเฉพาะ แทนฟอร์มเพิ่มทั่วไป (ดู src/components/RegistryPage.jsx)
  // statusField ใช้ txType (รับเข้าคลัง/เบิกออกจากคลัง) แสดงเป็นป้ายสี + กรองตามประเภทได้อัตโนมัติไปในตัว
  'reg-cheque': {
    key: 'reg-cheque',
    path: '/reg-cheque',
    emoji: '🏦',
    title: 'ทะเบียนคุมการเบิกจ่ายเล่มเช็ค',
    noun: 'รายการเล่มเช็ค',
    numberField: 'seq',
    numberLabel: 'ลำดับ',
    hideInsert: true,
    dateField: 'txDate',
    statusField: 'txType',
    statusColors: {
      'รับเข้าคลัง': 'bg-emerald-100 text-emerald-800',
      'เบิกออกจากคลัง': 'bg-orange-100 text-orange-800',
    },
    stockLedger: {
      inValue: 'รับเข้าคลัง', outValue: 'เบิกออกจากคลัง',
      sourceKey: 'sourceType', sourceOptions: ['ยอดรับมาจากปีงบก่อน', 'รับจากธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร สาขาธาตุนาเวง'],
      numFromKey: 'chequeFrom', numToKey: 'chequeTo', numFromLabel: 'เลขที่เช็ค ตั้งแต่', numToLabel: 'เลขที่เช็ค ถึง',
      qtyKey: 'bookQty', unitLabel: 'เล่ม',
      requesterKey: 'requester', requesterPositionKey: 'requesterPosition',
      defaultRequester: 'นางสาวพิไลวรรณ กุลมินทร์', defaultRequesterPosition: 'นักวิชาการสาธารณสุขชำนาญการ',
      fixedAccountNoKey: 'accountNo', fixedAccountNo: '820286422',
      fixedAccountNameKey: 'accountName', fixedAccountName: 'เงินทุนหมุนเวียน สอ.บ้านหนองสนม',
    },
    fields: [
      { key: 'seq', label: 'ลำดับ', type: 'text', auto: true },
      { key: 'txDate', label: 'วันที่ทำรายการ', type: 'date', required: true, list: true },
      { key: 'txType', label: 'ประเภทรายการ', type: 'select', options: ['รับเข้าคลัง', 'เบิกออกจากคลัง'], required: true, list: true },
      { key: 'sourceType', label: 'ที่มา (ตอนรับเข้าคลัง)', type: 'select', options: ['ยอดรับมาจากปีงบก่อน', 'รับจากธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร สาขาธาตุนาเวง'], list: true },
      { key: 'chequeFrom', label: 'เลขที่เช็ค ตั้งแต่', type: 'text', list: true, search: true },
      { key: 'chequeTo', label: 'เลขที่เช็ค ถึง', type: 'text', list: true, search: true },
      { key: 'bookQty', label: 'จำนวน (เล่ม)', type: 'text', list: true },
      { key: 'accountNo', label: 'เลขที่บัญชี', type: 'text', list: true },
      { key: 'accountName', label: 'ชื่อบัญชี', type: 'text', list: true },
      { key: 'requester', label: 'ผู้เบิกเช็ค', type: 'text', list: true },
      { key: 'requesterPosition', label: 'ตำแหน่งผู้เบิก', type: 'text' },
      { key: 'balanceAfter', label: 'คงเหลือ (เล่ม)', type: 'text', auto: true, list: true },
      { key: 'signer', label: 'ลายเซ็นผู้รับเช็ค', type: 'text' },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'FFFF00',
    reportColumns: ['txDate', 'txType', 'sourceType', 'chequeFrom', 'chequeTo', 'bookQty', 'accountNo', 'accountName', 'requester', 'balanceAfter'],
    reportLayout: [
      { key: 'txDate' }, { key: 'txType' }, { key: 'sourceType' },
      { group: 'เลขที่เช็ค', color: '00FFFF', keys: ['chequeFrom', 'chequeTo'] },
      { key: 'bookQty' }, { key: 'accountNo' }, { key: 'accountName' }, { key: 'requester' }, { key: 'balanceAfter' },
    ],
  },
  // แก้ไขฟังก์ชันให้เหมือนทะเบียนคุมเล่มเช็คด้านบน (รับเข้า/เบิกออก + คำนวณยอดคงเหลืออัตโนมัติ) ตามคำขอ — ต่างกันแค่ไม่มีเลขที่บัญชี/ชื่อบัญชีตายตัว (ใบเสร็จไม่มีเลขบัญชี)
  'reg-receipt': {
    key: 'reg-receipt',
    path: '/reg-receipt',
    emoji: '🧾',
    title: 'ทะเบียนคุมใบเสร็จรับเงิน',
    noun: 'รายการเล่มใบเสร็จ',
    numberField: 'seq',
    numberLabel: 'ลำดับ',
    hideInsert: true,
    dateField: 'txDate',
    statusField: 'txType',
    statusColors: {
      'รับเข้าคลัง': 'bg-emerald-100 text-emerald-800',
      'เบิกออกจากคลัง': 'bg-orange-100 text-orange-800',
    },
    stockLedger: {
      inValue: 'รับเข้าคลัง', outValue: 'เบิกออกจากคลัง',
      sourceKey: 'sourceType', sourceOptions: ['ยอดรับมาจากปีงบก่อน', 'ซื้อเล่มใบเสร็จใหม่'],
      numFromKey: 'receiptFrom', numToKey: 'receiptTo', numFromLabel: 'เลขที่ใบเสร็จ ตั้งแต่', numToLabel: 'เลขที่ใบเสร็จ ถึง',
      qtyKey: 'bookQty', unitLabel: 'เล่ม',
      requesterKey: 'requester', requesterPositionKey: 'requesterPosition',
      defaultRequester: 'นางสาวพิไลวรรณ กุลมินทร์', defaultRequesterPosition: 'นักวิชาการสาธารณสุขชำนาญการ',
    },
    fields: [
      { key: 'seq', label: 'ลำดับ', type: 'text', auto: true },
      { key: 'txDate', label: 'วันที่ทำรายการ', type: 'date', required: true, list: true },
      { key: 'txType', label: 'ประเภทรายการ', type: 'select', options: ['รับเข้าคลัง', 'เบิกออกจากคลัง'], required: true, list: true },
      { key: 'sourceType', label: 'ที่มา (ตอนรับเข้าคลัง)', type: 'select', options: ['ยอดรับมาจากปีงบก่อน', 'ซื้อเล่มใบเสร็จใหม่'], list: true },
      { key: 'receiptFrom', label: 'เลขที่ใบเสร็จ ตั้งแต่', type: 'text', list: true, search: true },
      { key: 'receiptTo', label: 'เลขที่ใบเสร็จ ถึง', type: 'text', list: true, search: true },
      { key: 'bookQty', label: 'จำนวน (เล่ม)', type: 'text', list: true },
      { key: 'requester', label: 'ผู้เบิกใบเสร็จ', type: 'text', list: true },
      { key: 'requesterPosition', label: 'ตำแหน่งผู้เบิก', type: 'text' },
      { key: 'balanceAfter', label: 'คงเหลือ (เล่ม)', type: 'text', auto: true, list: true },
      { key: 'signer', label: 'ลายเซ็นผู้รับใบเสร็จ', type: 'text' },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'FFFF00',
    reportColumns: ['txDate', 'txType', 'sourceType', 'receiptFrom', 'receiptTo', 'bookQty', 'requester', 'balanceAfter'],
    reportLayout: [
      { key: 'txDate' }, { key: 'txType' }, { key: 'sourceType' },
      { group: 'เลขที่ใบเสร็จ', color: '00FFFF', keys: ['receiptFrom', 'receiptTo'] },
      { key: 'bookQty' }, { key: 'requester' }, { key: 'balanceAfter' },
    ],
  },
  'reg-deeka': {
    key: 'reg-deeka',
    path: '/reg-deeka',
    emoji: '📑',
    title: 'ทะเบียนคุมฎีกาเบิกจ่าย',
    noun: 'ฎีกาเบิกจ่าย',
    numberField: 'deekaNo',
    numberLabel: 'เลขที่ฎีกา',
    dateField: 'deekaDate',
    fields: [
      { key: 'deekaNo', label: 'เลขที่ฎีกา', type: 'text', auto: true, list: true, search: true },
      { key: 'dikaRefNo', label: 'ฎีกาเลขที่', type: 'text', required: true, list: true, search: true },
      { key: 'deekaDate', label: 'วันที่', type: 'date', required: true, list: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'amount', label: 'จำนวนเงิน', type: 'text', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'B48EAD',
    reportColumns: ['deekaNo', 'dikaRefNo', 'deekaDate', 'subject', 'amount'],
  },
  // ทะเบียนใหม่ตามแบบฟอร์มตัวอย่างที่ส่งมา — เลขที่เกียรติบัตรไม่เติมศูนย์หน้า (numberDigits: 1) เช่น 1/2569, 2/2569 ...
  'reg-certificate': {
    key: 'reg-certificate',
    path: '/reg-certificate',
    emoji: '🏅',
    title: 'ทะเบียนคุมเลขที่เกียรติบัตร',
    noun: 'เกียรติบัตร',
    numberField: 'certNo',
    numberLabel: 'เลขที่เกียรติบัตร',
    numberDigits: 1,
    dateField: 'grantDate',
    fields: [
      { key: 'certNo', label: 'เลขที่เกียรติบัตร', type: 'text', auto: true, list: true, search: true },
      { key: 'grantDate', label: 'วันที่มอบ', type: 'date', required: true, list: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'recipient', label: 'ชื่อผู้รับ', type: 'text', required: true, list: true, search: true },
      { key: 'institute', label: 'สถาบัน', type: 'textarea', list: true, search: true },
      // แก้จากช่องพิมพ์เอง "ระหว่าง" เป็น 2 ช่องปฏิทินไทยตามคำขอ
      { key: 'periodFrom', label: 'การปฏิบัติงาน ระหว่างวันที่', type: 'date', list: true },
      { key: 'periodTo', label: 'ถึงวันที่', type: 'date', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
    reportColor: 'C5E0B4',
    reportColumns: ['certNo', 'grantDate', 'subject', 'recipient', 'institute', 'periodFrom', 'periodTo'],
  },
};
