// นิยามทะเบียน: เพิ่มทะเบียนใหม่ได้โดยเพิ่มค่าในไฟล์นี้ ไม่ต้องเขียนหน้าใหม่
const UNITS = ['ธุรการ', 'การเงินและบัญชี', 'พัสดุ', 'ส่งเสริมป้องกันควบคุมโรค', 'เวชปฏิบัติครอบครัว', 'ผู้อำนวยการ'];

export const REGISTRIES = {
  incoming: {
    key: 'incoming',
    path: '/incoming',
    title: 'ทะเบียนหนังสือรับ',
    noun: 'หนังสือรับ',
    numberField: 'receiveNo',
    numberLabel: 'เลขรับ',
    dateField: 'receiveDate',
    statusField: 'status',
    dueField: 'dueDate',
    doneStatus: 'ดำเนินการแล้ว',
    groupField: 'unit',
    statusColors: {
      'รอดำเนินการ': 'bg-amber-100 text-amber-800',
      'กำลังดำเนินการ': 'bg-blue-100 text-blue-800',
      'ดำเนินการแล้ว': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'receiveNo', label: 'เลขรับ', type: 'text', auto: true, list: true, search: true },
      { key: 'receiveDate', label: 'วันที่รับ', type: 'date', required: true, list: true },
      { key: 'docNo', label: 'เลขที่หนังสือ', type: 'text', required: true, list: true, search: true },
      { key: 'docDate', label: 'ลงวันที่', type: 'date' },
      { key: 'from', label: 'จาก', type: 'text', required: true, list: true, search: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'to', label: 'ถึง', type: 'text', search: true },
      { key: 'owner', label: 'ผู้รับผิดชอบ', type: 'text', list: true, search: true },
      { key: 'unit', label: 'กลุ่มงาน', type: 'select', options: UNITS },
      { key: 'urgency', label: 'ความเร่งด่วน', type: 'select', options: ['ปกติ', 'ด่วน', 'ด่วนมาก', 'ด่วนที่สุด'], default: 'ปกติ' },
      { key: 'secrecy', label: 'ชั้นความลับ', type: 'select', options: ['ปกติ', 'ลับ', 'ลับมาก', 'ลับที่สุด'], default: 'ปกติ' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['รอดำเนินการ', 'กำลังดำเนินการ', 'ดำเนินการแล้ว'], default: 'รอดำเนินการ', list: true },
      { key: 'dueDate', label: 'กำหนดดำเนินการ', type: 'date' },
      { key: 'actionDate', label: 'วันที่ดำเนินการ', type: 'date' },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
  },
  outgoing: {
    key: 'outgoing',
    path: '/outgoing',
    title: 'ทะเบียนหนังสือส่ง',
    noun: 'หนังสือส่ง',
    numberField: 'sendNo',
    numberLabel: 'เลขส่ง',
    dateField: 'sendDate',
    statusField: 'status',
    doneStatus: 'ส่งแล้ว',
    pendingStatus: 'ร่าง',
    groupField: 'unit',
    statusColors: {
      'ร่าง': 'bg-amber-100 text-amber-800',
      'ส่งแล้ว': 'bg-blue-100 text-blue-800',
      'ยืนยันรับแล้ว': 'bg-emerald-100 text-emerald-800',
    },
    fields: [
      { key: 'sendNo', label: 'เลขส่ง', type: 'text', auto: true, list: true, search: true },
      { key: 'sendDate', label: 'วันที่ส่ง', type: 'date', required: true, list: true },
      { key: 'docNo', label: 'เลขที่หนังสือ', type: 'text', required: true, list: true, search: true },
      { key: 'subject', label: 'เรื่อง', type: 'textarea', required: true, list: true, search: true },
      { key: 'receiver', label: 'ผู้รับ', type: 'text', list: true, search: true },
      { key: 'destOrg', label: 'หน่วยงานปลายทาง', type: 'text', required: true, list: true, search: true },
      { key: 'owner', label: 'ผู้รับผิดชอบ', type: 'text', search: true },
      { key: 'unit', label: 'กลุ่มงาน', type: 'select', options: UNITS },
      { key: 'method', label: 'วิธีส่ง', type: 'select', options: ['ไปรษณีย์', 'ส่งด้วยตนเอง', 'อีเมล', 'ระบบสารบรรณอิเล็กทรอนิกส์', 'อื่น ๆ'], default: 'ไปรษณีย์' },
      { key: 'status', label: 'สถานะ', type: 'select', options: ['ร่าง', 'ส่งแล้ว', 'ยืนยันรับแล้ว'], default: 'ร่าง', list: true },
      { key: 'note', label: 'หมายเหตุ', type: 'textarea' },
    ],
  },
};
